#!/usr/bin/env bash
#
# bootstrap-state.sh — create the Azure Storage account that holds Terraform
# state, then write infra/backend.hcl pointing at it.
#
# Run once per subscription. Safe to re-run: every step checks first, and the
# storage account name is derived from the subscription id, so the same
# subscription always resolves to the same account.
#
# This is the one piece of infrastructure Terraform cannot create for itself —
# it has to exist before there is anywhere to keep state.

set -euo pipefail

LOCATION="${LOCATION:-centralindia}"
STATE_RG="${STATE_RG:-rg-helios-tfstate}"
CONTAINER="${CONTAINER:-tfstate}"

here="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
backend_file="${here}/infra/backend.hcl"

if ! az account show >/dev/null 2>&1; then
  echo "Not signed in to Azure. Run 'az login' first." >&2
  exit 1
fi

subscription_id="$(az account show --query id --output tsv | tr -d '\r')"
subscription_name="$(az account show --query name --output tsv | tr -d '\r')"
suffix="$(echo "${subscription_id}" | tr -d '-' | tail -c 7 | tr '[:upper:]' '[:lower:]')"
account="sthelios${suffix}"

echo "Subscription: ${subscription_name}"
echo "State account: ${account}"
echo

if az group show --name "${STATE_RG}" >/dev/null 2>&1; then
  echo "Resource group ${STATE_RG} already exists."
else
  echo "Creating resource group ${STATE_RG}..."
  az group create --name "${STATE_RG}" --location "${LOCATION}" --output none
fi

if az storage account show --name "${account}" --resource-group "${STATE_RG}" >/dev/null 2>&1; then
  echo "Storage account ${account} already exists."
else
  echo "Creating storage account ${account}..."
  az storage account create \
    --name "${account}" \
    --resource-group "${STATE_RG}" \
    --location "${LOCATION}" \
    --sku Standard_LRS \
    --kind StorageV2 \
    --min-tls-version TLS1_2 \
    --allow-blob-public-access false \
    --output none
fi

# Blob versioning turns a corrupted or truncated state file from a disaster
# into an inconvenience.
az storage account blob-service-properties update \
  --account-name "${account}" \
  --resource-group "${STATE_RG}" \
  --enable-versioning true \
  --output none

if az storage container show \
     --name "${CONTAINER}" \
     --account-name "${account}" \
     --auth-mode login >/dev/null 2>&1; then
  echo "Container ${CONTAINER} already exists."
else
  echo "Creating container ${CONTAINER}..."
  az storage container create \
    --name "${CONTAINER}" \
    --account-name "${account}" \
    --auth-mode login \
    --output none
fi

cat > "${backend_file}" <<EOF
# Generated by scripts/bootstrap-state.sh. Not committed.
resource_group_name  = "${STATE_RG}"
storage_account_name = "${account}"
container_name       = "${CONTAINER}"
key                  = "helios.tfstate"
EOF

echo
echo "Wrote ${backend_file}"
echo "Next: make init"
